"""
Standalone scheduler layer for the Trend Agent.

This module ONLY calls `python main.py` and `python local_publish_html.py`
via subprocess. It never imports from news_agent or modifies pipeline internals.

The working directory is always the project root (parent of app/) so that
main.py can find config.py, news_agent/, etc.
"""
from __future__ import annotations

import json
from pathlib import Path
import re
import subprocess
import sys
from datetime import datetime, timezone

from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.schedulers.base import STATE_RUNNING

from app.scheduler_config import (
    DEFAULT_INTERVAL_HOURS,
    SCHEDULER_TYPE_INTERVAL,
    SCHEDULER_TYPE_ALARM,
)

# ── Paths ─────────────────────────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).resolve().parent.parent
MAIN_PY = PROJECT_ROOT / "main.py"
PUBLISH_SCRIPT = PROJECT_ROOT / "app" / "local_publish_html.py"
CONFIG_PATH = PROJECT_ROOT / "app" / "config.json"
STATUS_PATH = PROJECT_ROOT / "app" / "scheduler_status.json"

# Global scheduler — recreated on each update to avoid stale state
_scheduler: BackgroundScheduler | None = None


def _get_scheduler() -> BackgroundScheduler:
    """Return the current scheduler instance."""
    return _scheduler


# ── Status helpers ────────────────────────────────────────────────────────
def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _read_status() -> dict:
    if not STATUS_PATH.exists():
        return {}
    try:
        return json.loads(STATUS_PATH.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _write_status(**updates) -> None:
    try:
        payload = _read_status()
        payload.update(updates)
        STATUS_PATH.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    except Exception as e:
        print(f"Warning: could not write status file: {e}")


def load_scheduler_status() -> dict:
    payload = _read_status()
    payload.setdefault("last_triggered_at", None)
    payload.setdefault("last_main_status", "never")
    payload.setdefault("last_main_at", None)
    payload.setdefault("last_main_run_id", None)
    payload.setdefault("last_publish_status", "never")
    payload.setdefault("last_publish_at", None)
    payload.setdefault("last_publish_html", None)
    payload.setdefault("last_error", None)
    payload.setdefault("scheduler_status", "stopped")
    payload.setdefault("scheduler_type", SCHEDULER_TYPE_INTERVAL)
    payload.setdefault("scheduler_enabled", True)
    return payload


# ── Extract run_id from main.py JSON output ──────────────────────────────
def _extract_run_id(stdout: str) -> str | None:
    if not stdout:
        return None
    try:
        data = json.loads(stdout.strip().splitlines()[-1])
        return data.get("run_id")
    except (json.JSONDecodeError, IndexError):
        pass
    match = re.search(r'"run_id"\s*:\s*"([^"]+)"', stdout)
    return match.group(1) if match else None


# ── Find the HTML file generated by main.py ──────────────────────────────
def _find_generated_html(run_id: str) -> Path | None:
    blogs_dir = PROJECT_ROOT / "storage" / "blogs"
    if not blogs_dir.exists():
        return None
    candidates = sorted(
        blogs_dir.glob(f"*-{run_id}.html"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    return candidates[0] if candidates else None


# ── Publish generated HTML to PeopleNewsTime API ─────────────────────────
def _publish_html(cfg: dict, html_path: Path) -> bool:
    category_id = str(cfg.get("category_id") or "").strip()
    if not category_id:
        print("Skipping PeopleNewsTime publish: category_id not configured")
        _write_status(
            last_publish_status="skipped",
            last_publish_at=_now_iso(),
            last_error="category_id not configured",
        )
        return False

    publish_status = str(cfg.get("wordpress_status") or "draft").strip()

    cmd = [
        sys.executable,
        str(PUBLISH_SCRIPT),
        "--file", str(html_path),
        "--category-id", category_id,
        "--status", publish_status,
    ]

    print("\n" + "=" * 60)
    print("Publishing:", " ".join(cmd))
    print("=" * 60)

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        cwd=str(PROJECT_ROOT),
    )

    if result.stdout:
        print("PUBLISH STDOUT:", result.stdout)
    if result.stderr:
        print("PUBLISH STDERR:", result.stderr)

    if result.returncode != 0:
        _write_status(
            last_publish_status="failed",
            last_publish_at=_now_iso(),
            last_publish_html=str(html_path),
            last_error=f"local_publish_html.py exit code {result.returncode}",
        )
        return False

    _write_status(
        last_publish_status="success",
        last_publish_at=_now_iso(),
        last_publish_html=str(html_path),
        last_error=None,
    )
    return True


# ── Main job — calls python main.py via subprocess ───────────────────────
def run_job():
    """
    Run the news_agent pipeline by calling:
        python main.py --country "US" --topic-category sports --wordpress-sync --wordpress-status draft

    Then publish the generated HTML via local_publish_html.py.
    """
    try:
        _write_status(
            last_triggered_at=_now_iso(),
            last_main_status="running",
            last_publish_status="pending",
            last_error=None,
        )

        with open(CONFIG_PATH, "r") as f:
            cfg = json.load(f)

        cmd = [
            sys.executable,
            str(MAIN_PY),
            "--country", str(cfg.get("country", "US")),
            "--topic-category", str(cfg.get("topic_category", "business")),
            "--wordpress-sync",
            "--wordpress-status", str(cfg.get("wordpress_status", "draft")),
            "--trigger", "scheduler",
        ]

        print("\n" + "=" * 60)
        print("Running:", " ".join(cmd))
        print("Working dir:", str(PROJECT_ROOT))
        print("=" * 60)

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            cwd=str(PROJECT_ROOT),
        )

        if result.stdout:
            print("MAIN STDOUT:", result.stdout)
        if result.stderr:
            print("MAIN STDERR:", result.stderr)

        if result.returncode != 0:
            print(f"main.py exited with code {result.returncode}")
            _write_status(
                last_main_status="failed",
                last_main_at=_now_iso(),
                last_error=f"main.py exit code {result.returncode}",
                last_publish_status="skipped",
            )
            return

        run_id = _extract_run_id(result.stdout or "")
        _write_status(
            last_main_status="success",
            last_main_at=_now_iso(),
            last_main_run_id=run_id,
            last_error=None,
        )

        if run_id:
            html_path = _find_generated_html(run_id)
            if html_path:
                _publish_html(cfg, html_path)
            else:
                print(f"No HTML found for run_id={run_id} — skipping publish")
                _write_status(
                    last_publish_status="skipped",
                    last_publish_at=_now_iso(),
                    last_error=f"No HTML file for run_id={run_id}",
                )
        else:
            print("Could not extract run_id — skipping publish")
            _write_status(
                last_publish_status="skipped",
                last_publish_at=_now_iso(),
                last_error="Could not extract run_id from main.py output",
            )

    except Exception as e:
        print(f"Scheduler job failed: {e}")
        _write_status(
            last_main_status="failed",
            last_main_at=_now_iso(),
            last_error=str(e),
        )


# ── Scheduler lifecycle ──────────────────────────────────────────────────
def _shutdown_scheduler():
    """Completely shut down the current scheduler so no stale jobs remain."""
    global _scheduler
    if _scheduler is not None:
        try:
            _scheduler.shutdown(wait=False)
        except Exception:
            pass
        _scheduler = None


def _create_scheduler() -> BackgroundScheduler:
    """Create a fresh scheduler instance."""
    global _scheduler
    _scheduler = BackgroundScheduler()
    return _scheduler


# ── Scheduler configuration ──────────────────────────────────────────────
def update_scheduler():
    """
    Reconfigure the scheduler based on current config.json.

    IMPORTANT: This fully shuts down and recreates the scheduler on every
    call to prevent stale jobs from the previous mode leaking into the new one.

    Two scheduler types:
    - **interval**: Runs the job every N hours. Does NOT run immediately on
      save — waits for the first interval to pass.
    - **alarm**: Runs the job once at a specific date and time.
    """
    try:
        with open(CONFIG_PATH, "r") as f:
            cfg = json.load(f)

        scheduler_type = str(cfg.get("scheduler_type") or SCHEDULER_TYPE_INTERVAL).strip().lower()
        scheduler_enabled = bool(cfg.get("scheduler_enabled", True))

        # ── Always shut down the old scheduler completely ────────────
        # This prevents any leftover interval jobs from firing when
        # switching to alarm mode.
        _shutdown_scheduler()

        if not scheduler_enabled:
            _write_status(
                scheduler_status="stopped",
                scheduler_updated_at=_now_iso(),
                scheduler_type=scheduler_type,
                scheduler_enabled=False,
                last_error=None,
            )
            print("Scheduler DISABLED — no jobs scheduled")
            return

        # ── Create a fresh scheduler ─────────────────────────────────
        sched = _create_scheduler()

        # ── INTERVAL mode ────────────────────────────────────────────
        if scheduler_type == SCHEDULER_TYPE_INTERVAL:
            interval_hours = int(cfg.get("interval_hours") or DEFAULT_INTERVAL_HOURS)
            if interval_hours < 1:
                interval_hours = 1

            sched.add_job(
                run_job,
                trigger="interval",
                hours=interval_hours,
                # Do NOT set next_run_time — the first run will happen
                # after the first interval elapses, NOT immediately.
                id="trend_agent_interval",
                replace_existing=True,
            )

            sched.start(paused=False)

            _write_status(
                scheduler_status="running",
                scheduler_updated_at=_now_iso(),
                scheduler_type=scheduler_type,
                scheduler_interval_hours=interval_hours,
                scheduler_enabled=True,
                last_error=None,
            )
            print(f"Scheduler: INTERVAL — every {interval_hours} hour(s) (first run in {interval_hours}h)")

        # ── ALARM mode ───────────────────────────────────────────────
        elif scheduler_type == SCHEDULER_TYPE_ALARM:
            alarm_datetime = cfg.get("alarm_datetime")  # e.g. "2026-06-10T14:30"

            if not alarm_datetime:
                _write_status(
                    scheduler_status="error",
                    scheduler_updated_at=_now_iso(),
                    scheduler_type=scheduler_type,
                    scheduler_enabled=True,
                    last_error="No alarm datetime set — please set a date and time",
                )
                print("ERROR: No alarm datetime set. Please set a date and time in the UI.")
                return

            # Parse the datetime string
            try:
                run_time = datetime.fromisoformat(alarm_datetime)
            except ValueError:
                _write_status(
                    scheduler_status="error",
                    scheduler_updated_at=_now_iso(),
                    last_error=f"Invalid alarm datetime: {alarm_datetime}",
                )
                print(f"ERROR: Invalid alarm datetime format: {alarm_datetime}")
                return

            now = datetime.now()

            if run_time <= now:
                _write_status(
                    scheduler_status="error",
                    scheduler_updated_at=_now_iso(),
                    scheduler_type=scheduler_type,
                    scheduler_alarm_datetime=alarm_datetime,
                    scheduler_enabled=True,
                    last_error=f"Alarm time {alarm_datetime} is in the past — please choose a future time",
                )
                print(f"ERROR: Alarm time {alarm_datetime} is in the past. Please choose a future time.")
                return

            sched.add_job(
                run_job,
                trigger="date",
                run_date=run_time,
                id="trend_agent_alarm",
                replace_existing=True,
            )

            sched.start(paused=False)

            _write_status(
                scheduler_status="running",
                scheduler_updated_at=_now_iso(),
                scheduler_type=scheduler_type,
                scheduler_alarm_datetime=alarm_datetime,
                scheduler_enabled=True,
                last_error=None,
            )
            print(f"Scheduler: ALARM — will run at {alarm_datetime}")

        else:
            _write_status(
                scheduler_status="error",
                scheduler_updated_at=_now_iso(),
                last_error=f"Unknown scheduler type: {scheduler_type}",
            )
            print(f"ERROR: Unknown scheduler type '{scheduler_type}'")

    except Exception as e:
        print(f"Failed to update scheduler: {e}")
        _write_status(scheduler_status="error", last_error=str(e))


def start_scheduler():
    """Called on app startup to initialize the scheduler."""
    update_scheduler()
